name: Step Output Example

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Generate step output
        id: get_result
        run: echo "result=success" >> $GITHUB_OUTPUT

      - name: Consume step output
        run: echo "The result is ${{ steps.get_result.outputs.result }}"
